### ISSUE TITLE
ASCII 'k' highlighted as homoglyph in some file types

### ISSUE THREAD

**Issue by dhduvall** [Konfekt/vim-unicode-homoglyphs#2]
If I remove `\u212A` from the `K` homoglyphs, the problem goes away. Disabling all other plugins and removing everything from my `.vimrc` other than enabling syntax highlighting, plugins, and pathogen doesn't correct it.

The problem doesn't show up in all filetypes, but I've seen it in `markdown`, `html`, `dosini`, and a few others.

**Comment by Konfekt** [comment]
Thank you very much! I noticed it before, wondered why, but did not link it to my plug-in. Thank you for the fix. I hope we can live without highlighting the Kelvin sign, but by no means I understand why it caused the standard Latin small letter `k` to be highlighted.

**Comment by dhduvall** [comment]
I dug a bit more into the problem. Turns out it's an issue with case folding. The [unicode case folding spec](http://www.unicode.org/Public/UNIDATA/CaseFolding.txt) specifically has the Kelvin sign fold to an ASCII lowercase `k`. I won't begin to understand that, but vim takes that file and creates its own case folding routines based on it. In fact, I can reproduce it by simply setting `ignorecase` and searching for `\%u212a`, even with `-u NONE`.

This also explains why we only see the issue for some file types: some, but not all, syntax files run `syntax case ignore`, but once they do, it's on until `syntax case match`, so that's the mode that this plugin runs in.  Thus the fix is to turn off case-insensitive matching specifically for homoglyphs.

**Comment by Konfekt** [comment]
Thanks for this heads-up! It was intriguing indeed why it only occurred occasionally.
